tac_lite.tac_lite_scheme.*:
  type: config_entity
  label: 'TAC Lite Scheme config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Name'
    uuid:
      type: string
    permissions:
      type: sequence
      label: 'Permissions'
      sequence:
        type: string
    visibility:
      type: boolean
      label: 'Term visibility'
    grants:
      type: sequence
      label: 'Grants'
      sequence:
        type: sequence
        label: 'Vocabularies per role ID'
        sequence:
          type: sequence
          label: 'Terms per vocabulary ID'
          sequence:
            type: integer
            label: 'Term ID'
