id: tac_lite_settings
label: TAC Lite configuration
migration_tags:
  - Drupal 6
source:
  plugin: variable
  variables:
    - tac_lite_categories
process:
  categories:
    -
      plugin: migration
      migration: d6_taxonomy_vocabulary
      source: tac_lite_categories
    -
      plugin: skip_on_empty
      method: row
destination:
  plugin: config
  config_name: tac_lite.settings
migration_dependencies:
  required:
    - d6_taxonomy_vocabulary
